# -*- coding: utf-8 -*-
"""wsd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wd-noIE87fQH-eilYo_WVlxWQisOcwI6
"""

import math
from collections import defaultdict

# Step 1: Define training data
data = {
    "f": [("bass", "eat", "super"), ("bass", "lunch", "excellent"), ("bass", "eat", "like")],
    "m": [("bass", "play", "music"), ("bass", "interest", "play")]
}

# Step 2: Define vocabulary and test sentence
vocabulary = {"bass", "eat", "super", "lunch", "excellent", "like", "play", "music", "interest"}
test_sentence = {"bass", "super", "excellent", "play"}
total_words = len(vocabulary)

# Step 3: Initialize word counts and category counts
count_word_f = defaultdict(int)  # Stores word counts for "fish" category
count_word_m = defaultdict(int)  # Stores word counts for "music" category
count_of_f = 0  # Number of sentences in "fish" category
count_of_m = 0  # Number of sentences in "music" category
total_sentences = 0  # Total number of sentences

# Step 4: Count occurrences of words in each category
for sense in data:
    for sentence in data[sense]:  # ✅ Corrected loop
        total_sentences += 1  # Count total sentences

        if sense == "f":
            count_of_f += 1
            for word in sentence:
                count_word_f[word] += 1
        else:
            count_of_m += 1
            for word in sentence:
                count_word_m[word] += 1

# Step 5: Compute Prior Probabilities
prior_prob_f = count_of_f / total_sentences
prior_prob_m = count_of_m / total_sentences

# Step 6: Compute Log Probabilities for Each Category (Directly)
score_f = math.log10(prior_prob_f)  # Start with fish category probability
score_m = math.log10(prior_prob_m)  # Start with music category probability

# Step 7: Compute Conditional Probabilities without Function
for word in test_sentence:
    fish_prob = (count_word_f[word] + 1) / (count_of_f + total_words)  # Laplace smoothing
    music_prob = (count_word_m[word] + 1) / (count_of_m + total_words)  # Laplace smoothing

    score_f += math.log10(fish_prob)
    score_m += math.log10(music_prob)

# Step 8: Print Scores Before Making the Decision
print(f"Final Score for 'Fish' category: {score_f}")
print(f"Final Score for 'Music' category: {score_m}")

# Step 9: Determine the Sense of "bass"
if score_f > score_m:
    print("The sense of 'bass' is: Fish.")
else:
    print("The sense of 'bass' is: Music.")

